# adder_AUTOGEN.toml

[block]
name        = "adder_AUTOGEN"
fullpath    = ""              
tag         = "dsp:adder_AUTOGEN"
label       = "dsp"
sim_type    = 4               # Scicos computational function type
blocktype   = "c"             # c-block
graphics    = { width = 4, height = 8, style = "shape=rectangle;fillColor=green" }

# ------------------------------------------
# parameter definitions: variable name, type, default, label, help text
# ------------------------------------------
[[block.parameters]]
name        = "blkname"
type        = "str"
default     = "adder_AUTOGEN"
label       = "Block Name"
help        = "Any string to identify the block"

[[block.parameters]]
name        = "a_bitwidth"
type        = "intvec"
default     = 32
label       = "Input bit width (a)"
help        = "Width in bits for port a"

[[block.parameters]]
name        = "b_bitwidth"
type        = "intvec"
default     = 32
label       = "Input bit width (b)"
help        = "Width in bits for port b"

[[block.parameters]]
name        = "c_bitwidth"
type        = "intvec"
default     = 32
label       = "Output bit width (c)"
help        = "Width in bits for port c"

# ------------------------------------------
# input ports: name, default rows, default cols, implicit/explicit
# ------------------------------------------
[[block.inputs]]
name        = "in0"
rows        = 1
cols_param  = "a_bitwidth"
implicit    = false

[[block.inputs]]
name        = "in1"
rows        = 1
cols_param  = "b_bitwidth"
implicit    = false

# output ports
[[block.outputs]]
name        = "out0"
rows        = 1
cols_param  = "c_bitwidth"
implicit    = false
