loadXcosLibs;

// load the scilab functions
getd('scilab_library/scilab_blocks/utils');

// TODO: load the xps and dsp blocks automatically
// all of the blocks in the scilab_library/casper_xps and 
// scilab_library/casper_dsp directories should be loaded autocaically

// add casper xps blocks
debug_info('------Loading CASPER XPS...------');
// load the xps blocks
getd('scilab_library/scilab_blocks/casper_xps');

// create the blocks
rfsoc4x2_inst = rfsoc4x2("define");
gpio_inst = gpio("define");
swreg_out_inst = swreg("define");
rfdc_inst = rfdc("define");
sbram_inst = sbram("define");
// add the blocks to the palette
cur_dir = pwd();
xps_fig_dir = cur_dir + '/scilab_library/scilab_blocks/casper_xps/figures/';
pal = xcosPal("CASPER XPS");
pal = xcosPalAddBlock(pal, rfsoc4x2_inst, xps_fig_dir + 'rfsoc4x2.png', xps_fig_dir + 'rfsoc4x2.png');
pal = xcosPalAddBlock(pal, gpio_inst);
pal = xcosPalAddBlock(pal, swreg_out_inst);
pal = xcosPalAddBlock(pal, rfdc_inst);
pal = xcosPalAddBlock(pal, sbram_inst);
//pal = xcosPalAddBlock(pal, swreg_out_inst);
xcosPalAdd(pal);
debug_info('------ CASPER XPS loaded --------');

// add casper dsp blocks
debug_info('------Loading CASPER DSP...------');
// load the xps blocks
getd('scilab_library/scilab_blocks/casper_dsp');

// add autogenered casper dsp blocks for testing
debug_info('------Loading AUTOGENERATED CASPER DSP...------');
getd('scilab_library/scilab_blocks/casper_dsp_autogen');


// add AUTOGENERATED casper dsp blocks for testing
adder_AUTOGEN_inst = adder_AUTOGEN("define");
slice_AUTOGEN_inst = slice_AUTOGEN("define");

cur_dir = pwd();
dsp_fig_dir = cur_dir + '/scilab_library/scilab_blocks/casper_dsp/figures/';
pal = xcosPal("CASPER DSP [AUTOGEN]");
pal = xcosPalAddBlock(pal, adder_AUTOGEN_inst);
pal = xcosPalAddBlock(pal, slice_AUTOGEN_inst);
xcosPalAdd(pal);
debug_info('------ CASPER DSP [AUTOGEN] loaded --------');

// create the blocks

adder_inst = adder("define");
edge_detect_inst = edge_detect("define");
counter_inst = counter("define");
pulse_ext_inst = pulse_ext("define");
slice_inst = slice("define");
munge_inst = munge("define");
wbfft_inst = wbfft("define");
bus_expand_inst = bus_expand("define");
dsp_constant_inst = dsp_constant("define");

cur_dir = pwd();
dsp_fig_dir = cur_dir + '/scilab_library/scilab_blocks/casper_dsp/figures/';
pal = xcosPal("CASPER DSP");
pal = xcosPalAddBlock(pal, adder_inst);
pal = xcosPalAddBlock(pal, pulse_ext_inst);
pal = xcosPalAddBlock(pal, edge_detect_inst);
pal = xcosPalAddBlock(pal, counter_inst);
pal = xcosPalAddBlock(pal, slice_inst);
pal = xcosPalAddBlock(pal, munge_inst);
pal = xcosPalAddBlock(pal, wbfft_inst);
pal = xcosPalAddBlock(pal, bus_expand_inst);
pal = xcosPalAddBlock(pal, dsp_constant_inst);
xcosPalAdd(pal);
debug_info('------ CASPER DSP loaded --------');

// add casper sim blocks
debug_info('------Loading CASPER SIM...------');
// load the xps blocks
getd('scilab_library/scilab_blocks/casper_sim');
/*
exec('scilab_library/scilab_blocks/casper_sim/sim_constant.sci');
exec('scilab_library/scilab_blocks/casper_sim/scope.sci');
exec('scilab_library/scilab_blocks/casper_sim/sim.sci');
exec('scilab_library/scilab_blocks/casper_sim/sine.sci');
*/
// create the blocks
sim_constant_inst = sim_constant("define");
scope_inst = scope("define");
sim_inst = sim("define");  
sine_inst = sine("define");
cur_dir = pwd();
sim_fig_dir = cur_dir + '/scilab_library/scilab_blocks/casper_sim/figures/';
pal = xcosPal("CASPER SIM");
pal = xcosPalAddBlock(pal, sim_constant_inst, sim_fig_dir + 'constant.png', sim_fig_dir + 'constant.png');
pal = xcosPalAddBlock(pal, scope_inst, sim_fig_dir + 'scope.png', sim_fig_dir + 'scope.png');
pal = xcosPalAddBlock(pal, sine_inst, sim_fig_dir + 'sine.png', sim_fig_dir + 'sine.png');
pal = xcosPalAddBlock(pal, sim_inst, sim_fig_dir + 'sim.png', sim_fig_dir + 'sim.png');

xcosPalAdd(pal);
debug_info('------ CASPER SIM loaded --------');